# Generated by Django 4.2.7 on 2026-05-04 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(choices=[('#6C63FF', 'Фиолетовый'), ('#FF6584', 'Розовый'), ('#43E97B', 'Зелёный'), ('#FFA726', 'Оранжевый'), ('#26C6DA', 'Голубой'), ('#EF5350', 'Красный'), ('#AB47BC', 'Лиловый'), ('#FFD600', 'Жёлтый')], default='#6C63FF', max_length=10)),
                ('icon', models.CharField(default='📁', max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
    ]
