# Generated by Django 4.2.7 on 2026-05-04 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=10)),
                ('category', models.CharField(choices=[('tasks', 'Задачи'), ('streak', 'Серии'), ('pomodoro', 'Помодоро'), ('projects', 'Проекты'), ('special', 'Особое')], default='special', max_length=20)),
                ('condition_type', models.CharField(max_length=50)),
                ('condition_value', models.IntegerField(default=1)),
                ('xp_reward', models.IntegerField(default=50)),
                ('coins_reward', models.IntegerField(default=25)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('theme', 'Тема'), ('avatar_frame', 'Рамка аватара'), ('badge', 'Значок')], max_length=20)),
                ('icon', models.CharField(default='🎨', max_length=10)),
                ('price_coins', models.IntegerField(default=100)),
                ('value', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('coins', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('max_streak', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('pomodoros_completed', models.IntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('character_class', models.CharField(choices=[('warrior', 'Воин'), ('mage', 'Маг'), ('ninja', 'Ниндзя'), ('archer', 'Лучник')], default='warrior', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Игровой профиль',
                'verbose_name_plural': 'Игровые профили',
            },
        ),
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('quest_type', models.CharField(max_length=30)),
                ('target_value', models.IntegerField(default=1)),
                ('current_value', models.IntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=30)),
                ('coins_reward', models.IntegerField(default=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('is_equipped', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.shopitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'item')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='LeagueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('xp_earned', models.IntegerField(default=0)),
                ('tasks_done', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-xp_earned'],
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
